# Generated by Django 4.2.30 on 2026-09-13 23:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessVertical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('issuer', models.CharField(blank=True, max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=60, unique=True)),
                ('job_title', models.CharField(max_length=160)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('availability', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('PRE_AGREEMENT', 'Pré-accord'), ('ON_MISSION', 'En mission'), ('UNAVAILABLE', 'Indisponible')], default='AVAILABLE', max_length=20)),
                ('validation_status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté')], default='DRAFT', max_length=20)),
                ('average_score', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certifications', models.ManyToManyField(blank=True, to='orbit_app.certification')),
            ],
        ),
        migrations.CreateModel(
            name='ExpertiseDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpertRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('min_language_level', models.CharField(blank=True, max_length=2)),
                ('max_daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('desired_start', models.DateField(blank=True, null=True)),
                ('duration_days', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumise'), ('WAITING_MATCHING', 'Matching'), ('WAITING_PRE_AGREEMENT', 'Pré-accord'), ('WAITING_PO', 'PO attendu'), ('IN_PROGRESS', 'En cours'), ('WAITING_EVALUATION', 'Évaluation'), ('CLOSED', 'Clôturée'), ('CANCELLED', 'Annulée')], default='DRAFT', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orbit_app.expertisedomain')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='transactions/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('PO', 'Bon de commande'), ('PV', 'Procès-verbal')], max_length=2)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_documents', to='orbit_app.expertrequest')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subsidiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subsidiaries', to='orbit_app.cluster')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='orbit_app.expertisedomain')),
            ],
        ),
        migrations.CreateModel(
            name='RequestDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='requests/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('RFP', 'RFP'), ('RFI', 'RFI'), ('EOI', 'EOI'), ('OTHER', 'Autre')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='orbit_app.expertrequest')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('client', models.CharField(blank=True, max_length=160)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='orbit_app.expert')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('DEMANDEUR', 'Demandeur'), ('ADMIN_DEMANDEUR', 'Administrateur demandeur'), ('ADMIN_FOURNISSEUR', 'Administrateur fournisseur'), ('ADMIN_OMEA', 'Administrateur OMEA')], default='DEMANDEUR', max_length=30)),
                ('subsidiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='orbit_app.subsidiary')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('url', models.CharField(blank=True, max_length=300)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('planned_end_date', models.DateField()),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planifiée'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], default='PLANNED', max_length=20)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='orbit_app.expert')),
                ('po_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_missions', to='orbit_app.transactiondocument')),
                ('pv_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pv_missions', to='orbit_app.transactiondocument')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='mission', to='orbit_app.expertrequest')),
                ('supplier_subsidiary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orbit_app.subsidiary')),
            ],
        ),
        migrations.CreateModel(
            name='ExpertSolicitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPTED', 'Acceptée'), ('REFUSED', 'Refusée'), ('EXPIRED', 'Expirée'), ('ESCALATED', 'Escaladée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=15)),
                ('deadline', models.DateTimeField()),
                ('response_reason', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('reminders_sent', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitations', to='orbit_app.expert')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitations', to='orbit_app.expertrequest')),
            ],
        ),
        migrations.AddField(
            model_name='expertrequest',
            name='required_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orbit_app.language'),
        ),
        migrations.AddField(
            model_name='expertrequest',
            name='required_skills',
            field=models.ManyToManyField(blank=True, to='orbit_app.skill'),
        ),
        migrations.AddField(
            model_name='expertrequest',
            name='subsidiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='orbit_app.subsidiary'),
        ),
        migrations.CreateModel(
            name='ExpertLanguageAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orbit_app.expert')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orbit_app.language')),
            ],
        ),
        migrations.AddField(
            model_name='expert',
            name='domains',
            field=models.ManyToManyField(blank=True, to='orbit_app.expertisedomain'),
        ),
        migrations.AddField(
            model_name='expert',
            name='languages',
            field=models.ManyToManyField(blank=True, through='orbit_app.ExpertLanguageAssignment', to='orbit_app.language'),
        ),
        migrations.AddField(
            model_name='expert',
            name='skills',
            field=models.ManyToManyField(blank=True, to='orbit_app.skill'),
        ),
        migrations.AddField(
            model_name='expert',
            name='subsidiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experts', to='orbit_app.subsidiary'),
        ),
        migrations.AddField(
            model_name='expert',
            name='verticals',
            field=models.ManyToManyField(blank=True, to='orbit_app.businessvertical'),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('mission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation', to='orbit_app.mission')),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('old_status', models.CharField(blank=True, max_length=40)),
                ('new_status', models.CharField(blank=True, max_length=40)),
                ('metadata', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='expertlanguageassignment',
            constraint=models.UniqueConstraint(fields=('expert', 'language'), name='unique_expert_language'),
        ),
    ]
