# Generated by Django 4.2.30 on 2026-09-23 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orbit_app', '0002_unify_affiliate_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertrequest',
            name='mode',
            field=models.CharField(choices=[('BROADCAST', 'Diffuser aux filiales'), ('DIRECT', 'Solliciter un expert précis')], default='BROADCAST', max_length=12),
        ),
        migrations.AddField(
            model_name='expertrequest',
            name='target_expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direct_requests', to='orbit_app.expert'),
        ),
        migrations.CreateModel(
            name='BroadcastProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='broadcast_proposals', to='orbit_app.expert')),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='broadcast_proposals', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='orbit_app.expertrequest')),
            ],
        ),
        migrations.AddConstraint(
            model_name='broadcastproposal',
            constraint=models.UniqueConstraint(fields=('request', 'expert'), name='unique_broadcast_proposal'),
        ),
    ]
