# Generated by Django 4.2.30 on 2026-09-24 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orbit_app', '0003_expertrequest_mode_expertrequest_target_expert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertsolicitation',
            name='desired_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expertsolicitation',
            name='duration_days',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='expertsolicitation',
            name='max_daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='expertsolicitation',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expertsolicitation',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='expertsolicitation',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitations', to='orbit_app.expertrequest'),
        ),
    ]
